### ISSUE TITLE
bert as embedding

### ISSUE THREAD

**Issue by bourne-3** [bplank/bilstm-aux#20]
i use python3 embeds/bert.prep.py  ,then it generate a folder named bert. Then i run the command "python3 embeds/bert.py".Unfortunately, it output a sentence"please provide embeddings , conl file and port". But the folder bert contain five files.( bert_config  ,bert_model.ckpt.index, bert_model.ckpt.data,  bert_model.ckpt.meta, vocab)Which one i should input?

**Comment by robvanderg** [comment]
You would run it as:
python3 embeds/bert.py embeds/bert train.conllu 8888

And then it would write a file train.conllu.bert, which includes the embeddings generated by multi-lingual bert in the misc column.

However, it should be noted that this functionality has not been thoroughly tested.

**Comment by bourne-3** [comment]
yeah,it works! But the result with pretrain embedding is worser than the one which without it.

**Comment by bplank** [comment]
what tensorflow version for bert-as-service is working? It seems that package is not working on python 3.8.x and tf 2.3.x?

**Comment by robvanderg** [comment]
Hmm, I forgot. However, I think it might not make so much sense anymore to use this. Because 1) performance doesnt seem to increase 2) bert-as-a-service is a bit overkill for this usage 3) debugging this would be at least as much effort as changing the code to something simpler. 

Perhaps we should look into using the transformers library instead? If you want I can create a script that appends the embeddings to the tab-separated file again?, or would you like to include it in the code directly?

**Comment by bplank** [comment]
Hi Rob!
Yes looks like the BERT-as-service is buggy. I refactored the code and before pushing did some tests. With Elmo it works and improves.

> Perhaps we should look into using the transformers library instead? If you want I can create a script that appends the embeddings to the tab-separated file again?, or would you like to include it in the code directly?

As we have set it up earlier, appended embeddings to the tab-separated file :) 👍

**Comment by bplank** [comment]
this is now supported, merged into main branch
